config:
  plugins:
    metrics-by-endpoint: {}
  target: "http://localhost:8080"
  phases:
    - duration: 10
      arrivalRate: 5
scenarios:
  - name: "Session flow (register + login)"
    flow:
      - log: "creo variables para usuario de prueba"
      - get: 
          url: "/mockingproducts/user"
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
            - json: "$.age"
              as: "age"
            - json: "$.role"
              as: "role"
      - log: "registrando al usuario"
      - post:
          url: "/session/register"
          json:
            first_name: "{{ first_name}}"
            last_name: "{{ last_name}}"
            email: "{{ email}}"
            password: "{{ password}}" 
            age: "{{ age}}"
            role: "{{ role}}"
      - think : 5
      - log: "login user"
      - post:
          url: "/session/login"
          json:
            email: "{{ email}}"
            password: "{{ password}}" 
