
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:
    product:
      type: object
      properties:
        id:
          type: number
          format: int32
          unique: true
          description: El ID del producto.
        title:
          type: string
          description: El título del producto.
        description:
          type: string
          description: La descripción del producto.
        code:
          type: string
          description: El código del producto.
        price:
          type: number
          description: El precio del producto.
        status:
          type: boolean
          default: true
          description: El estado del producto (activo o inactivo).
        stock:
          type: number
          description: La cantidad en stock del producto.
        category:
          type: string
          description: La categoría del producto.
        thumbnail:
          type: array
          description: La lista de miniaturas del producto.
        owner:
          type: string
          default: "admin"
          description: El propietario del producto.
      example:
        id: 1
        title: "Producto 1"
        description: "Descripción del producto 1"
        code: "P1"
        price: 19.99
        status: true
        stock: 100
        category: "Electrónica"
        thumbnail: ["thumbnail1.jpg", "thumbnail2.jpg"]
        owner: "admin"

paths:
  /products:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/product'
          example:
            - id: 1
              title: "Producto 1"
              description: "Descripción del producto 1"
              code: "P1"
              price: 19.99
              status: true
              stock: 100
              category: "Electrónica"
              thumbnail: ["thumbnail1.jpg", "thumbnail2.jpg"]
              owner: "admin"
            - id: 2
              title: "Producto 2"
              description: "Descripción del producto 2"
              code: "P2"
              price: 29.99
              status: true
              stock: 50
              category: "Ropa"
              thumbnail: ["thumbnail3.jpg"]
              owner: "user@example.com"
        '500':
          description: Error en el servidor
    post:
      summary: Agregar un nuevo producto
      security:
        - basicAuth: [] 
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        '400':
          description: Campos requeridos faltantes o inválidos
        '500':
          description: Error en el servidor

  /products/{id}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Productos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
          description: El ID del producto que se desea obtener.
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          example:
            id: 1
            title: "Producto 1"
            description: "Descripción del producto 1"
            code: "P1"
            price: 19.99
            status: true
            stock: 100
            category: "Electrónica"
            thumbnail: ["thumbnail1.jpg", "thumbnail2.jpg"]
            owner: "admin"
        '404':
          description: Producto no encontrado
          content:
            application/json:
              example:
                status: error
                error: Producto no encontrado
        '500':
          description: Error en el servidor
    delete:
      summary: Eliminar un producto por ID
      security:
        - basicAuth: [] 
      tags:
        - Productos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
          description: El ID del producto que se desea eliminar.
      responses:
        '200':
          description: Producto eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              example:
                status: error
                error: Producto no encontrado
        '500':
          description: Error en el servidor
    put:
      summary: Actualizar un producto por ID
      security:
        - basicAuth: [] 
      tags:
        - Productos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int32
          description: El ID del producto que se desea actualizar.
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          example:
            id: 1
            title: "Producto actualizado"
            description: "Descripción actualizada"
            code: "P1"
            price: 24.99
            status: true
            stock: 75
            category: "Electrónica"
            thumbnail: ["thumbnail1.jpg", "thumbnail2.jpg"]
            owner: "admin"
        '404':
          description: Producto no encontrado
          content:
            application/json:
              example:
                status: error
                error: Producto no encontrado
        '500':
          description: Error en el servidor



    